### ISSUE TITLE
Review new rules in stylelint 9.5.0, select which ones we want and don't, and upgrade dependency

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/stylelint-config-wikimedia#70]
While updating some dev dependencies such as https://gerrit.wikimedia.org/r/457098/ I am getting:

`npm WARN stylelint-config-wikimedia@0.4.3 requires a peer of stylelint@9.2.0 but none was installed`

`stylelint` latest stable version is `9.5.0` according to https://www.npmjs.com/package/stylelint

Maybe we should make it compatible with our own package as well?

Thanks.

**Comment by jdforrester** [comment]
This is intentional; will re-title to explain the work involved.

**Comment by MarcoAurelioWM** [comment]
Perfect, thanks.
-- 
M. A.

**Comment by Volker-E** [comment]
List to consider since v9.2.0:
- 9.2.1: will relieve us from an error on webkit pseudo classes with fixed `selector-pseudo-class-no-unknown`
- 9.3.0: [`keyframes-name-pattern`](https://stylelint.io/user-guide/rules/keyframes-name-pattern/#keyframes-name-pattern) probably no. Could use some Wikimedia standardization, although it's quite some work and I don't see this as prio right now.
- 9.3.0: [`media-feature-name-value-whitelist`](https://stylelint.io/user-guide/rules/media-feature-name-value-whitelist/#media-feature-name-value-whitelist) probably no. Could come in very handy to restrict wild growth of media feature query values, but probably better off in a per-project environment
- 9.4.0: [`linebreaks`](https://stylelint.io/user-guide/rules/linebreaks/#linebreaks) maybe?
- 9.5.0: only autofixes and bug fixes
- 9.6.0: [`no-empty-first-line`](https://stylelint.io/user-guide/rules/no-empty-first-line/#no-empty-first-line): yes
- 9.7.0, 9.7.1 & 9.8.0 no new options added

**Comment by edg2s** [comment]
> linebreaks maybe?

Definitely. It's probably already mentioned in the style guide.

Agree with the rest too.

**Comment by jdforrester** [comment]
OK, decision made. I upgraded us to 9.8.0 in #78; we'll add `linebreaks` and consider this closed.
